// src/components/Banner/Banner.tsx
import React, { useEffect } from 'react';

declare const $: any;

const Banner: React.FC = () => {
  useEffect(() => {
    if ($('.venobox').venobox) {
      $('.venobox').venobox({
        //
      });
    }

    // if ($('.your-slick-class').slick) {
    //   $('.your-slick-class').slick({
    //   });
    // }

  }, []);

  return (
    <section id="banner">
      <div id="backtotop">
        <a href="#banner" id="backtotop-value"><i className="fa-solid fa-arrow-up"></i></a>
      </div>
      <div className="container zindex">
        <div className="row">
          <div className="col-lg-6 banner-txt">
            <span>The Ultimate</span>
            <h3>Comic</h3>
            <h3 className="txt-pos">Book.</h3>
            <a href="#" className="button-primary">Read Now</a>
            {/* <a
              className="venobox button-circular"
              data-autoplay="true"
              data-vbtype="video"
              href="https://www.youtube.com/watch?v=kmh1cr3b4Js"
            >
              <i className="fa-solid fa-play"></i>
            </a> */}
            <div className="row banner-review">
              <div className="col-lg-3">
                <img src="/assets/images/user5.png" alt="user" className="one" />
                <img src="/assets/images/user1.png" alt="user" />
                <img src="/assets/images/user2.png" alt="user" />
              </div>
              <div className="col-lg-4">
                <div className="stars">
                  <i className="fa-solid fa-star"></i>
                  <i className="fa-solid fa-star"></i>
                  <i className="fa-solid fa-star"></i>
                  <i className="fa-solid fa-star"></i>
                  <i className="fa-solid fa-star-half-stroke"></i>
                </div>
                <p>(409.6K Reviews)</p>
              </div>
            </div>
          </div>
          <div className="col-10 col-sm-11 col-md-7 col-lg-6 banner-images">
            <img src="/assets/images/banner-icon.png" alt="banner-icon" className="banner-icon" />
            <img src="/assets/images/banner2.png" alt="banner-img" className="banner-img one img-fluid" />
            <img src="/assets/images/banner1.png" alt="banner-img" className="banner-img two img-fluid" />
          </div>
        </div>
      </div>
     {/* <div className="marquee">
        <span className="marquee-1">
          <span className="text">Comic Book<img src="/assets/images/star.png" alt="star" /></span>
          <span className="text">Comic Arts<img src="/assets/images/star.png" alt="star" /></span>
          <span className="text">Comic Book<img src="/assets/images/star.png" alt="star" /></span>
          <span className="text">Comic Arts<img src="/assets/images/star.png" alt="star" /></span>
          <span className="text">Comic Book<img src="/assets/images/star.png" alt="star" /></span>
          <span className="text">Comic Arts<img src="/assets/images/star.png" alt="star" /></span>
          <span className="marquee-2">
            <span className="text">Comic Book<img src="/assets/images/star.png" alt="star" /></span>
            <span className="text">Comic Arts<img src="/assets/images/star.png" alt="star" /></span>
            <span className="text">Comic Book<img src="/assets/images/star.png" alt="star" /></span>
            <span className="text">Comic Arts<img src="/assets/images/star.png" alt="star" /></span>
            <span className="text">Comic Book<img src="/assets/images/star.png" alt="star" /></span>
            <span className="text">Comic Arts<img src="/assets/images/star.png" alt="star" /></span>
          </span>
        </span>
      </div>*/}
    </section>
  );
};

export default Banner;

// src/app/shared/components/banner/banner.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-banner',
  templateUrl: './banner.component.html',
  standalone: true,
  styleUrl: './banner.component.css'
})
export class BannerComponent {

}

<!-- BANNER AREA START -->
<section id="banner">
  <div id="backtotop">
    <a href="#banner" id="backtotop-value"><i class="fa-solid fa-arrow-up"></i></a>
  </div>
  <div class="container zindex">
    <div class="row">
      <div class="col-lg-6 banner-txt">
        <span>The Ultimate</span>
        <h3>Comic</h3>
        <h3 class="txt-pos">Book.</h3>
        <a class="button-primary" href="#">Read Now</a>
        <a class="venobox button-circular" data-autoplay="true" data-vbtype="video"
           href="https://www.youtube.com/watch?v=kmh1cr3b4Js"><i class="fa-solid fa-play"></i></a>
        <div class="row banner-review">
          <div class="col-lg-3">
            <img alt="user" class="one" src="assets/images/user5.png">
            <img alt="user" src="assets/images/user1.png">
            <img alt="user" src="assets/images/user2.png">
          </div>
          <div class="col-lg-4">
            <div class="stars">
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star-half-stroke"></i>
            </div>
            <p>(409.6K Reviews)</p>
          </div>
        </div>
      </div>
      <div class="col-10 col-sm-11 col-md-7 col-lg-6 banner-images">
        <img alt="banner-icon" class="banner-icon" src="assets/images/banner-icon.png">
        <img alt="banner-img" class="banner-img one img-fluid" src="assets/images/banner2.png">
        <img alt="banner-img" class="banner-img two img-fluid" src="assets/images/banner1.png">
      </div>
    </div>
  </div>
  <div class="marquee">
			<span class="marquee-1">
				<span class="text">Comic Book<img alt="star" src="assets/images/star.png"></span>
				<span class="text">Comic Arts<img alt="star" src="assets/images/star.png"></span>
				<span class="text">Comic Book<img alt="star" src="assets/images/star.png"></span>
				<span class="text">Comic Arts<img alt="star" src="assets/images/star.png"></span>
				<span class="text">Comic Book<img alt="star" src="assets/images/star.png"></span>
				<span class="text">Comic Arts<img alt="star" src="assets/images/star.png"></span>
				<span class="marquee-2">
					<span class="text">Comic Book<img alt="star" src="assets/images/star.png"></span>
					<span class="text">Comic Arts<img alt="star" src="assets/images/star.png"></span>
					<span class="text">Comic Book<img alt="star" src="assets/images/star.png"></span>
					<span class="text">Comic Arts<img alt="star" src="assets/images/star.png"></span>
					<span class="text">Comic Book<img alt="star" src="assets/images/star.png"></span>
					<span class="text">Comic Arts<img alt="star" src="assets/images/star.png"></span>
				</span>
			</span>
  </div>
</section>
<!-- BANNER AREA ENDS -->
